### ISSUE TITLE
Problem when I refresh and I lock 

### ISSUE THREAD

**Issue by Yannmagie** [stom79/mastalab#132]
Hello! 
I write you this morning in Google play and you invited me to create an issues, what I do :)

My first problem is when I open the application, I see in news feeds (house icon) the second toot instead of seeing the first toot. I don't know if it is just for me but this is very strange. 

My second problem is I use zenui launcher (because I have zenfone) with lock application who are integrated and often, the application crash when I unlock the application. I think is because the lock are in front of the application and it not like it or is a problem of zenui launcher.

It's over now thank you for your response!

**Comment by stom79** [comment]
Thanks for opening this issue on github. I have only 500 characters for replying on Google (even in the beta channel) and it's not really appropriated for a discussion concerning bugs.

>  My first problem is when I open the application, I see in news feeds (house icon) the second toot instead of seeing the first toot. I don't know if it is just for me but this is very strange.

Yes. I need to fix that. It's due to the bookmark. In fact, the app will remember your previous position and will always start at this position. Unfortunately, there is small offset of one toot.

> My second problem is I use zenui launcher (because I have zenfone) with lock application who are integrated and often, the application crash when I unlock the application.

I will try to reproduce that bug and fix it asap. 

Thanks for this report.

**Comment by Yannmagie** [comment]
perfect!
thank you for your work on this app that evolves day by day!
