### ISSUE TITLE
Error message for 2FA accounts is unhelpful

### ISSUE THREAD

**Issue by vpzomtrrfrt** [stom79/mastalab#174]
I tried to login to Mastalab, and it gave a generic failure message.  It was only after trying to login from a browser that I remembered that I was using 2FA, and therefore should click the link for that.  It'd be nice for this error to be more helpful, or just to have support for 2FA in the app.

---

Instance: mess.casa

Mastalab version: 1.6.8

Android version: 7.1.2

**Comment by stom79** [comment]
It's not really simple, because if authentication failed, the response will be the same:

`{"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}`

Not sure it will be really helpful to display it.

But I could provide a list of actions if it fails:
- Check if the instance is not down
- Authentication with 2FA
- etc.
