### ISSUE TITLE
Battery issues on Android

### ISSUE THREAD

**Issue by smonff** [stom79/mastalab#226]
Last version of Mastalab from F-Droid is using 43% of the battery on a Nexus 5 that runs an up-to-date standard LineageOS. I also used Twidere, Tusky and Tootdon and they didn't behave this way, even in case of extreme use of the fediverse.

Instance: https://anticapitalist.party, https://computerfairi.es
Note that I mostly use the first one. When activating the second account, the battery consumption is even greater.

Mastalab version: 1.7.0, also used 1.6.9

Android version: LineageOS 14.1-20180103-NIGHTLY-hammerhead  / Android 7.1.2

**Comment by stom79** [comment]
This ugly issue is related to the bug with notifications which is fixed in 1.7.1. A lock was missing and several sockets could be opened for a same account which obviously created battery drain. Of course, with multiple accounts, it amplified this issue.
You can stop live notifications and restart the app to fix this issue with release 1.7.0. Or you can test the [release 1.7.1](https://github.com/stom79/mastalab/releases/tag/1.7.1). But you need to uninstall the app due to signatures.

**Comment by stom79** [comment]
Fixed in 1.7.4
