### ISSUE TITLE
Add support for using "custom tabs" of external browser

### ISSUE THREAD

**Issue by jfmcbrayer** [stom79/mastalab#297]
Both Chrome and Firefox on Android now support a mode called "custom tabs". These let an app open a link in a fast-opening subset of the browser, which is themed according to the calling app. These provide more features than the internal WebView (in particular, Firefox custom tabs use any passive extensions like uBlock Origin, SSL Everywhere, or Decentraleyes), but load faster than the full browser.

Mastalab should try to use custom tabs when the internal browser is turned off.

**Comment by stom79** [comment]
The purpose of the built-in browser is to display web pages without any connections to other browsers (cookies/history/etc). Of course, due to cache it can be longer to load but it ensures more privacy. Our behavior with browsers is not the same when using it in social media because we click on targeted links (posted by others). 
Of course, what I can do, it's to add a third option with "[custom tabs](https://developer.chrome.com/multidevice/android/customtabs)".

**Comment by jfmcbrayer** [comment]
FWIW, I spent several hours trying to get custom tabs working, without success. But at least I now have a working build environment! (And I'm researching the problem I'm having.)

**Comment by stom79** [comment]
I tested and it works.

**Comment by jfmcbrayer** [comment]
Yeah, I'm pretty sure the problem with mine was pulling in the wrong API version of com.android.support:customtabs. Oh well. It was a learning experience.

**Comment by stom79** [comment]
My bad, I need to clean the [build.gradle](https://github.com/stom79/mastalab/blob/30105fa6031c0c5f4b33f1cf53de63ce15c31cc0/app/build.gradle#L38-L53) and use variables. Because I manually wrote release versions for each libs (27.0.2)...

**Comment by stom79** [comment]
I added this option by default when the built-in browser is disabled (there is a checkbox so it can also be disabled).

**Comment by jfmcbrayer** [comment]
Nice, fast work. Thanks.
