### ISSUE TITLE
Feature request: option to reverse the order in the timeline

### ISSUE THREAD

**Issue by brabalan** [stom79/mastalab#35]
I read my toots in chronological order. But since newer toots are above older ones, I need to do a lot of scrolling for long toots: scrolling down to read it, then up to get to the next one.

Could there be an option to reverse the order, oldest toots at the top?

**Comment by stom79** [comment]
The main problem will be for getting oldest toots. First I need to deactivate the pull to refresh because, the scroll up will be used to get them (when we are at the top). Also, I don't know what will be the behavior during the first load, because I need to quickly move the cursor  to the end (which is by default at the position: zero) to avoid an automatic load of older ones.

**Comment by stom79** [comment]
I think that this request is connected to #34 and it is about how toots are read. It will be hard to make both mechanisms live together without having edge effects.
I think the best solution would be to add an activity dedicated for reading toots from the last seen (displayed at the top) to the newest (at the bottom).

Toots are loaded by 40. So the app can't know where you stopped to read between these 40 toots. We can imagine a kind of bookmark that allows to start reading again from it. This bookmark could be added manually by the user or if a toot is touched (with a record only if new_id > last_id).

**Comment by brabalan** [comment]
A bookmark would be a great solution. The features are related, but #34 is more important for me (not missing toots), #35 is about convenience.

**Comment by stom79** [comment]
I think that the bookmark (cf #34) is the closest solution for this issue.
