### ISSUE TITLE
Keep position?

### ISSUE THREAD

**Issue by ve4grm** [stom79/mastalab#85]
Hi Tom. I'm trying to figure out if there's a way to get Mastalab to save my position when I reopen the app. It always seems to want to reload the timeline, and shuffle me to the top.

I was reading #34 with interest, as it references a "bookmark" feature, but I can't tell if that's implemented?

Thanks for your help!

---

Instance: dice.camp

Mastalab version: 1.6.4.1
Set to notify me on new notifications, but not all new posts if that matters?

Android version: 7.0
Mastalab is set to ignore battery optimizations, as well.

**Comment by stom79** [comment]
Hi,

#34 is not yet implemented. I started to work on this feature but I got troubles when getting client id and I had to remove a library. Then I worked on some edge effects...
But this is the number one of enhancements I want to work on. But due to the way pagination works with API, I can only suggest this approach: 

https://github.com/stom79/mastalab/issues/34#issuecomment-343993447

I will let you know.

**Comment by ve4grm** [comment]
Of course, thank you. The ability to keep your place between sessions is the number 1 feature I'm looking for in a Mastodon client, and the one that no client seems to have yet. I'm looking forward to what you come up with.

**Comment by stom79** [comment]
I pushed an apk for tests. See my [comment](https://github.com/stom79/mastalab/issues/34#issuecomment-349729481) in #34

**Comment by stom79** [comment]
Solved in #34
